[tools]
# "github:open-telemetry/opentelemetry-collector-releases" = { version = "latest", version_prefix = "cmd/builder/v" }
"github:nats-io/nats-server" = "latest"
"github:nats-io/natscli" = "latest"
go = "1.25"
nsc = "latest"
"go:go.opentelemetry.io/collector/cmd/builder" = "latest"
"go:github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen" = "latest"
