dist:
  module: github.com/m3nowak/otelcol-nats/dist/otelcol-nats
  name: otelcol-nats
  description: OpenTelemetry Collector with OTLP distro components and OTLP over
    NATS JetStream components
  output_path: ./otelcol-nats
  build_tags: grpcnotrace

exporters:
  - gomod: github.com/m3nowak/otelcol-nats v0.0.0
    import: github.com/m3nowak/otelcol-nats/exporter/otlpnatsjetstreamexporter
    path: ..
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.150.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.150.0

receivers:
  - gomod: github.com/m3nowak/otelcol-nats v0.0.0
    import: github.com/m3nowak/otelcol-nats/receiver/otlpnatsjetstreamreceiver
    path: ..
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.150.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.56.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.56.0
