services:
  lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

  nats:
    image: docker.io/library/nats:2.12.7
    command: [ "-js" ]
    ports:
      - "4222:4222"
